import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdea2",
        "secondary-fixed": "#b0f0ce",
        "secondary": "#2c694e",
        "tertiary": "#32618f",
        "on-secondary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#134976",
        "tertiary-fixed": "#d1e4ff",
        "inverse-primary": "#f5be45",
        "on-primary-fixed-variant": "#5c4200",
        "background": "#fcf9f5",
        "primary": "#7a5900",
        "surface-container-low": "#f6f3f0",
        "secondary-fixed-dim": "#95d4b3",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e5e2df",
        "outline": "#817663",
        "on-error": "#ffffff",
        "surface-bright": "#fcf9f5",
        "surface": "#fcf9f5",
        "inverse-on-surface": "#f3f0ed",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#003860",
        "on-secondary-container": "#306e53",
        "surface-dim": "#dcdad6",
        "error": "#ba1a1a",
        "on-primary-container": "#483300",
        "surface-tint": "#7a5900",
        "tertiary-fixed-dim": "#9dcafe",
        "primary-container": "#c9971e",
        "surface-variant": "#e5e2df",
        "on-tertiary": "#ffffff",
        "outline-variant": "#d3c5af",
        "on-surface": "#1b1c1a",
        "on-secondary-fixed-variant": "#0d5138",
        "on-background": "#1b1c1a",
        "tertiary-container": "#76a2d4",
        "secondary-container": "#adeecb",
        "primary-fixed-dim": "#f5be45",
        "inverse-surface": "#31302e",
        "surface-container": "#f0edea",
        "on-surface-variant": "#4f4635",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#261900",
        "surface-container-high": "#eae8e4",
        "on-tertiary-fixed": "#001d35"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "16px",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "unit": "8px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "label-caps": ["var(--font-space-grotesk)"],
        "display-lg": ["var(--font-space-grotesk)"],
        "headline-md": ["var(--font-space-grotesk)"],
        "headline-lg": ["var(--font-space-grotesk)"],
        "display-lg-mobile": ["var(--font-space-grotesk)"],
        "body-lg": ["var(--font-hanken-grotesk)"],
        "body-md": ["var(--font-hanken-grotesk)"],
        "display": ["var(--font-space-grotesk)"],
        "sans": ["var(--font-hanken-grotesk)"],
      },
      fontSize: {
        "label-caps": ["14px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
